# Copyright (c) 2024, Oracle and/or its affiliates.
# DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
#
# This code is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License version 2 only, as
# published by the Free Software Foundation.
#
# This code is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
# version 2 for more details (a copy is included in the LICENSE file that
# accompanied this code).
#
# You should have received a copy of the GNU General Public License version
# 2 along with this work; if not, write to the Free Software Foundation,
# Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
#
# Please contact Oracle, 500 Oracle Parkway, Redwood Shores, CA 94065 USA
# or visit www.oracle.com if you need additional information or have any
# questions.
#
# Continuous Integration Workflow for adaptivemm
#
# Note: based on libcgroup's continuous-integration.yml
#

name: Adaptivemm Continuous Integration
on: ["push", "pull_request"]

jobs:
  was-modified:
    name: Was adaptivemm or adaptived modified?
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      adaptived: ${{ steps.filter.outputs.adaptived }}
      adaptivemm: ${{ steps.filter.outputs.adaptivemm }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            adaptived: 
              - 'adaptived/**'
            adaptivemm:
              - '*.c'
              - '*.h'
              - '*.cfg'
              - '*.service'
              - '*.spec'
              - '*.yaml'
              - 'Makefile'
              - '*.md'
              - '*.txt'
              - '*.preset'
              - 'adaptivemmd.8'

  # If there was a change to adaptived, then adaptivemm should be unmodified
  adaptivemm-unchanged:
    name: Adaptivemm should be unchanged if this patch has adaptived commits
    needs: was-modified
    if: |
      github.event_name == 'pull_request'
      ${{ needs.was-modified.outputs.adaptived == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build the current adaptivemm executable
        run: |
          make
          sha256sum -b adaptivemmd > adaptivemmd.SHA256

      - name: Show GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Check out the commit prior to this change
        env:
          COMMIT_COUNT: ${{ github.event.commits }}
        run: |
          git fetch origin
          git checkout HEAD~$COMMIT_COUNT

      - name: Build the previous adaptivemm executable
        run: |
          make
          sha256sum -c adaptivemmd.SHA256
